#!/usr/bin/env bash

if [ ${#} -ne 2 ]
then
  echo "Usage: $0 <cog-name> <Red-DiscordBot Folder>"
  exit 1
else
  COG=$1
  REDFOLDER=$2
fi

if [ ! -d ${PWD}/${COG} ]
then
  echo "ERROR: ${COG} cog doesn't exist."
  exit 2
fi

if [ ! -d ${REDFOLDER} ]
then
  echo "ERROR: Can't find RedBot on ${REDFOLDER}"
  exit 3
fi

if [ -d  ${COG}/data ]
then
  mkdir ${REDFOLDER}/data/${COG}
  cd ${COG}/data
  find . -type d -exec mkdir -p ${REDFOLDER}/data/${COG}/{} \;
  find . -type f -exec ln -Fs ${PWD}/{} ${REDFOLDER}/data/${COG}/{} \;
  cd -
fi

find ${PWD}/${COG} -type f -maxdepth 1 -name '*.py' -exec ln -Fs {} ${REDFOLDER}/cogs \;

